vpc_cidr_block         = "10.0.0.0/16"
subnet_cidr_block      = "10.0.1.0/24"
avail_zone             = "me-central-1a"
env_prefix             = "dev"
instance_type          = "t3.micro"
my_public_key_location = "MyLabKey.pub"
private_key_location   = "MyLabKey.pem"